services:
  app:
    container_name: meduzzen-front-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: npm run start -- --host 0.0.0.0
