services:
  app:
    container_name: meduzzen-front-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    ports:
      - '${PORT}:${PORT}'

volumes:
  node_modules:
