services:
  app:
    container_name: meduzzen-front-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - '${NG_APP_APP_PORT}:${NG_APP_APP_PORT}'
    restart: always
    command: npm run start -- --host 0.0.0.0
