services:
  app:
    container_name: meduzzen-front-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - '${PORT}:${PORT}'
    restart: always
    command: npm run start -- --host 0.0.0.0
